FROM kolaente/upx AS upx
FROM ghcr.io/graalvm/native-image AS native

WORKDIR /usr/src/app

COPY app.jar .
COPY resource-config.json .
COPY reflectconfig.json .  
COPY config.edn .

# Compile into a native binary
COPY devops/compile.sh .

RUN chmod +x compile.sh

COPY --from=upx /usr/local/bin/upx /usr/local/bin/upx
RUN ./compile.sh
RUN upx -6 /usr/src/app/app && ls -ah app
  
FROM gcr.io/distroless/base:latest

ENV PORT="8080"

ENV HOST="0.0.0.0"

EXPOSE 8080

COPY --from=native /usr/src/app/app /

COPY config.edn .

# Run the app
CMD ["/app", "init"]
