FROM docker.io/cimg/clojure:1.10.3 AS builder

USER circleci

WORKDIR /home/circleci/project

COPY . .

# Compile into a uberjar
RUN clojure -X:depstar

FROM kolaente/upx AS upx
FROM ghcr.io/graalvm/native-image AS native

WORKDIR /usr/src/app

COPY --from=builder /home/circleci/project/app.jar /usr/src/app/app.jar
COPY resource-config.json .
COPY reflectconfig.json .
COPY config.edn .

# Compile into a native binary
COPY devops/compile.sh .

RUN chmod +x compile.sh

RUN ./compile.sh
COPY --from=upx /usr/local/bin/upx /usr/local/bin/upx
# RUN upx -6 /usr/src/app/app && ls -ah app

FROM gcr.io/distroless/base:latest

ENV PORT="8080"

ENV HOST="0.0.0.0"

EXPOSE 8080

COPY --from=native /usr/src/app/app /

COPY config.edn .

# Run the app
CMD ["/app", "init"]
