FROM docker.io/cimg/clojure:1.10.3 AS builder

USER circleci

WORKDIR /home/circleci/project

COPY deps.edn .
RUN clojure -Spath

COPY src src
COPY resources resources
COPY config.edn config.edn

# Compile into a uberjar
RUN clojure -X:depstar

# FROM amazoncorretto:17
FROM gcr.io/distroless/java17-debian11

ENV PORT="8080"

ENV HOST="0.0.0.0"

EXPOSE 8080

COPY --from=builder /home/circleci/project/app.jar .

COPY config.edn .

# Run the app
CMD ["java", "app.jar", "init"]
