FROM ghcr.io/graalvm/native-image:22.0.0 AS native

USER root

WORKDIR /usr/src/app

COPY app.jar .
COPY resource-config.json .
COPY reflectconfig.json .

# Compile into a native binary
COPY devops/compile.sh .

RUN chmod +x compile.sh

RUN ./compile.sh

FROM gcr.io/distroless/base:latest

ENV PORT="8080"

ENV HOST="0.0.0.0"

EXPOSE 8080

COPY --from=native /usr/src/app/app /

COPY config.edn .

# Run the app
CMD ["/app", "init"]
